# Generated by Django 5.2.1 on 2025-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('rfid', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
